[package]
name = "robust"
version = "0.2.5"
edition = "2024"

[dependencies]
steady_state     = {version = "0.2.5", features = ["exec_async_std", "telemetry_server_builtin"]}
clap             = { version = "4.5.41", features = ["derive"] }


